In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.10.0


In [3]:
x = tf.Variable(0.0)
x_plus = tf.assign_add(x, 1)

In [4]:
init = tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [5]:
with tf.control_dependencies([x_plus]):
    y_group = x
    y_group_opt = tf.group(y_group)
    
    y_identity_opt=tf.identity(x)

In [6]:
with tf.Session() as session:
    init.run()
    for i in range(5):
        session.run(y_group_opt)
        print(session.run(y_group))
        print(session.run(y_identity_opt))

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [3]:
input_place = tf.placeholder(shape=(None,4,3), dtype='float32')
output_place = tf.layers.flatten(input_place)

In [16]:
print(input_place)
print(output_place)
print( output_place.get_shape()[1].value )

Tensor("Placeholder:0", shape=(?, 4, 3), dtype=float32)
Tensor("flatten/Reshape:0", shape=(?, 12), dtype=float32)
12


In [41]:
t1 = [[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]]
t2 = [[[5,5,5],[6,6,6]],[[7,7,7],[8,8,8]]]
t3 = tf.concat([t1, t2], axis=-1)

In [42]:
with tf.Session() as session:
    tf.initialize_all_variables().run()
    print(session.run(t3))

[[[1 1 1 5 5 5]
  [2 2 2 6 6 6]]

 [[3 3 3 7 7 7]
  [4 4 4 8 8 8]]]


In [3]:
input_holder = tf.placeholder(dtype=tf.float32, name='input', shape=[1, 2])

In [4]:
with tf.variable_scope(name_or_scope="scope_0", dtype=tf.float32):
    w1 = tf.get_variable(
        name='w1', 
        shape=[2, 2], 
        dtype=tf.float32, 
        initializer=tf.constant_initializer([[0,0],[1,1]]),
        trainable=True
    )
    b1 = tf.get_variable(
        name='b1',
        shape=[1, 2],
        dtype=tf.float32,
        initializer=tf.random_uniform_initializer(-1,1),
        trainable=True
    )
    o1 = tf.add( tf.matmul(input_holder, w1), b1 )
    
    w2 = tf.get_variable(
        name="w2",
        shape=[2, 3],
        dtype=tf.float32,
        initializer=tf.constant_initializer([[4,4,4],[3,3,3]]),
        trainable=True
    )
    b2 = tf.get_variable(
        name='b2',
        shape=[1, 3],
        dtype=tf.float32,
        initializer=tf.random_normal_initializer(-1,1),
        trainable=True
    )
    o2 = tf.add( tf.matmul(o1, w2), b2 )

In [5]:
gradient = tf.gradients(o2, input_holder)

In [6]:
list_var = tf.get_collection( tf.GraphKeys.GLOBAL_VARIABLES, scope='scope_0' )

In [8]:
save_h = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    display(sess.run(gradient, feed_dict={input_holder:[[1,2]]}))
    save_h.save(sess, './test_variale')
    for var in list_var:
        display(sess.run(var.value()))

[array([[36., 99.]], dtype=float32)]

array([[1., 2.],
       [4., 5.]], dtype=float32)

array([[-0.38562202, -0.15654874]], dtype=float32)

array([[2., 2., 2.],
       [5., 5., 5.]], dtype=float32)

array([[-0.8421599 , -0.29188538, -1.2433362 ]], dtype=float32)

In [7]:
save_h = tf.train.Saver()

In [8]:
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    
    list_var = tf.get_collection( tf.GraphKeys.GLOBAL_VARIABLES, scope='scope_0' )
    for var in list_var:
        display(sess.run(var.value()))
        
    save_h.restore(sess, './test_variale')
    
    list_var = tf.get_collection( tf.GraphKeys.GLOBAL_VARIABLES, scope='scope_0' )
    for var in list_var:
        display(sess.run(var.value()))

Instructions for updating:
Use `tf.global_variables_initializer` instead.


array([[0., 0.],
       [1., 1.]], dtype=float32)

array([[-0.21566272, -0.9949472 ]], dtype=float32)

array([[4., 4., 4.],
       [3., 3., 3.]], dtype=float32)

array([[-2.1522036 ,  0.50479794, -0.32831913]], dtype=float32)

INFO:tensorflow:Restoring parameters from ./test_variale


array([[1., 2.],
       [4., 5.]], dtype=float32)

array([[-0.38562202, -0.15654874]], dtype=float32)

array([[2., 2., 2.],
       [5., 5., 5.]], dtype=float32)

array([[-0.8421599 , -0.29188538, -1.2433362 ]], dtype=float32)

In [11]:
saver = tf.train.Saver(
    max_to_keep=,
    keep_checkpoint_every_n_hours=
)
saver.save(
    sess=,
    save_path=,
    global_step=,
    write_meta_graph=,
)

saver = tf.train.import_meta_graph( '*.meta' )
saver.restore(
    sess,
    tf.train.latest_checkpoint('./')
)

graph = tf.get_default_graph()
graph.get_tensor_by_name( 'w1:0' )

In [26]:
with tf.Session() as sess:
    display(sess.run(tf.random_normal([10], mean=0, stddev=0.0008)))

array([ 1.3046898e-03,  7.7915197e-04,  1.1418957e-03,  8.7922742e-04,
       -1.3859597e-03, -1.6696237e-04, -1.4350954e-03,  1.4423671e-03,
        3.0131005e-05, -4.0210065e-04], dtype=float32)